### PR TITLE
adds esp32-4827s043C-smartdisplay

### PR DESCRIPTION
**Pull request by aam335**

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Code looks fine. Can i have a screenshot on how the ui looks to double check if it's scaled properly?

**Comment by aam335** [comment]
image
image
image
image

**Comment by suchmememanyskill** [comment]
Mostly looks fine, although i don't think the bottom in the temp panel should be cut off. Could you play with the font size and minimum button height to fix that?

**Comment by aam335** [comment]
image
image

CYD_SCREEN_MIN_BUTTON_HEIGHT_PX 40->35 heaters and keyboard looks fine

**Comment by suchmememanyskill** [comment]
LGTM, please commit it so i can merge this. Thank you!

**Pull request merged**
