### PR TITLE
Supporting IP or Hostname

### PR DESCRIPTION
**Pull request by matthawley**
This adds support to the keyboard during the "ip" setup to also support a hostname entry instead. It uses a custom keyboard allowing for the characters `0-9`, `a-z`, `-` and `.`.

Build can be tested using https://github.com/matthawley/CYD-Klipper/actions/runs/7771755561

### CODE REVIEW

**Comment by matthawley** [comment]
Change associated with bug #27

**Comment by suchmememanyskill** [comment]
Would you mind rebasing the PR to go to the setup-ports branch? That's currently where all new features live

Other than that, LGTM

**Comment by matthawley** [comment]
Alright, rebased and changed upstream branch. I also set it up to use 2 different keyboards so that the ip/hostname can use the custom keyboard and the port will use the number keyboard.

**Comment by matthawley** [comment]
:D I royally screwed something up. I'll be re-creating this.

**Pull request closed without merging**
