### PR TITLE
Some visual UI tweaks for ESP32-8048S043C

### PR DESCRIPTION
**Pull request by themacboy**
CHANGES:

· Increased font size and small font size to 22 and 14 respectivelly.
· Increased side bar to 80px

Examples view:

20240302_130222_HDR

20240302_130237_HDR

20240302_130322_HDR

20240302_130248_HDR

### CODE REVIEW

**Comment by themacboy** [comment]
Just FYI... in the gcode listing the CPU load easily goes to 100% easily and the frame rate drops to 5 fps.

But I understand that this is normal due to the limitations of the ESP32 and the higher screen resolution.

**Comment by suchmememanyskill** [comment]
I think this still looks a little small. Will do some suggested changes in a second.

The dropdown in settings looks broken. I've noticed this on my 3.5 inch model but never fixed it. Will do so now

**Comment by themacboy** [comment]
Probably min button size can be greater too, but I prefer to wait because Im sure that @suchmememanyskill will add more and more option every day hehehe

Another time thanks for this great project.

**Comment by suchmememanyskill** [comment]
@themacboy Could you rebase or merge the latest changes into your 4.3inch branch? This should fix the dropdown being so cramped.

After that, could you give the following configuration a try?

```
        "-DCYD_SCREEN_GAP_PX=15",
        "-DCYD_SCREEN_MIN_BUTTON_HEIGHT_PX=60",
        "-DCYD_SCREEN_MIN_BUTTON_WIDTH_PX=60",
        "-DCYD_SCREEN_FONT=lv_font_montserrat_22",
        "-DCYD_SCREEN_FONT_SMALL=lv_font_montserrat_16",
        "-DCYD_SCREEN_SIDEBAR_SIZE_PX=70",
```

Also i wonder if the font should go from 22 to 24, to my eye it looks a little smaller than i expect

**Comment by themacboy** [comment]
> @themacboy Could you rebase or merge the latest changes into your 4.3inch branch? This should fix the dropdown being so cramped.

Yes It was done before the PR.  No? Sorry Im not really skilled with git process


> After that, could you give the following configuration a try?
> 
> ```
>         "-DCYD_SCREEN_GAP_PX=15",
>         "-DCYD_SCREEN_MIN_BUTTON_HEIGHT_PX=60",
>         "-DCYD_SCREEN_MIN_BUTTON_WIDTH_PX=60",
>         "-DCYD_SCREEN_FONT=lv_font_montserrat_22",
>         "-DCYD_SCREEN_FONT_SMALL=lv_font_montserrat_16",
>         "-DCYD_SCREEN_SIDEBAR_SIZE_PX=70",
> ```
> 
> Also i wonder if the font should go from 22 to 24, to my eye it looks a little smaller than i expect. Edit: checked it against my 3.5 inch version and based on the esp chip size itself it looks about the same. Probably a fine font size

Sure !!! I go

**Comment by suchmememanyskill** [comment]
> Yes It was done before the PR. No? Sorry Im not really skilled with git process

No, i did that after the PR when i saw your screenshots

https://github.com/themacboy/CYD-Klipper/tree/4.3inch
image
A button should appear in the red circle that allows you to merge the latest changes

**Comment by themacboy** [comment]
> Yeah, 800x480 is an insane amount of pixels to render for an esp. On the 3.5 inch display (480*320) i get 5fps when i don't push the display clock to the max

I checked that the expensive CPU usage is due to the horizontal scrolling of the file with a large filename

This would probably be solved by using multiple lines for the long name.

I have seen that the vertical displacement supports the displacement much better than when it is done horizontal linea linea

**Comment by themacboy** [comment]
> > Yes It was done before the PR. No? Sorry Im not really skilled with git process
> 
> No, i did that after the PR when i saw your screenshots
> 
> https://github.com/themacboy/CYD-Klipper/tree/4.3inch image A button should appear in the red circle that allows you to merge the latest changes

Oh sorry hahaha now I understand you hehehe thx

**Comment by suchmememanyskill** [comment]
> I checked that the expensive CPU usage is due to the horizontal scrolling of the file with a large filename

It's not the whole story. The screen will still heavily lag when scrolling the screen.
The ESP32 has no GPU. So all rendering is done on the CPU, which is very slow. In CYD-Klipper, one core is deddicated to rendering

**Comment by themacboy** [comment]
Dropdown adjustement:

image

**Comment by themacboy** [comment]
> > After that, could you give the following configuration a try?
> > ```
> >         "-DCYD_SCREEN_GAP_PX=15",
> >         "-DCYD_SCREEN_MIN_BUTTON_HEIGHT_PX=60",
> >         "-DCYD_SCREEN_MIN_BUTTON_WIDTH_PX=60",
> >         "-DCYD_SCREEN_FONT=lv_font_montserrat_22",
> >         "-DCYD_SCREEN_FONT_SMALL=lv_font_montserrat_16",
> >         "-DCYD_SCREEN_SIDEBAR_SIZE_PX=70",
> > ```

image

image

image

image


Really looks better ! ;)

**Pull request merged**
