### PR TITLE
Add emergency stop and full filename options

### PR DESCRIPTION
**Pull request by rorosaurus**
Both are optional using global configs.

Full filename removes scrolling the filename when showing 1) the list of printable items and 2) the current printing gcode.

Emergency stop hits the proper estop endpoint, as well as sending the `M112` command for good measure.
https://moonraker.readthedocs.io/en/latest/web_api/#emergency-stop

PXL_20240814_174552319 MP

### CODE REVIEW

**Comment by rorosaurus** [comment]
Don't merge yet! I just realized I need to fix the behavior when showing certain stats on the progress screen :)

**Comment by suchmememanyskill** [comment]
Hm, don't know about the styling of the button, it doesn't match any other button in the project currently. Could you give the button the alternate color profile button? (Iirc i implemented this in the printer panel).

Also don't know about the placement, the screen is starting to look very crowded. How does it look with just the no extras shown?

**Comment by rorosaurus** [comment]
For the color, I was trying to mimic how Mainsail/Fluidd/etc. have estop as red despite theme/style changes, which I think it appropriate given how disruptive it can be. I chose the outline because the solid red felt a little aggressive. Thoughts?

PXL_20240816_215549374 MP

Here it is with no extras shown:

PXL_20240816_214321778 MP

I agree it looks crowded with all the extras and full filename shown. I put these behind a setting though, so people can customize it how they like. I'm thinking it might encourage us to consolidate the "only layer" info screen into the same corner as the other extras, though, which is a departure from your design. Thoughts?

I have the larger 3.5 capacitive screen that I am using mainly, which should have room to display all this nicely I expect. Speaking of which, is there an easy way to do a local development OTA update to a device flashed with the latest public release? Or I would have had to upload my own build with changed JSON first? I'm rorosaurus on discord if you prefer to chat!

**Comment by suchmememanyskill** [comment]
I like that filled in red button a lot more.

For the layout of the screen, yeah maybe it should be re-designed now with all those extras. I would like for it to look good on the 2.8 inch models primarily. I'll see if i can think of something hopefully soon.

For the ota update, no, you can only push dev builds via usb. I haven't looked into local ota yet, may be a good idea

**Comment by suchmememanyskill** [comment]
LGTM, fully tested and verified

**Pull request merged**
